"""Create relay schema

Revision ID: 02eb272120f8
Revises:
"""

import sqlalchemy as sa

from alembic import op

revision = "02eb272120f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_rate_limits_expires_at"),
        "rate_limits",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "username",
            sa.String(length=64, collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("is_operator", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "domains",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "name",
            sa.String(length=253, collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.Column(
            "active_name",
            sa.String(length=253, collation="utf8mb4_bin"),
            nullable=True,
        ),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')"),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_name"),
    )
    op.create_index(
        op.f("ix_domains_owner_user_id"),
        "domains",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_invitations_user_id"),
        "invitations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "smtp_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_smtp_credentials_user_id"),
        "smtp_credentials",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "web_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_web_sessions_expires_at"),
        "web_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_web_sessions_user_id"),
        "web_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "credential_scopes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("credential_id", sa.String(length=36), nullable=False),
        sa.Column("domain_id", sa.String(length=36), nullable=False),
        sa.Column(
            "address",
            sa.String(length=254, collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["smtp_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "domain_id", "address"),
    )
    op.create_table(
        "domain_admins",
        sa.Column("domain_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("domain_id", "user_id"),
    )
    op.create_table(
        "send_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("credential_id", sa.String(length=36), nullable=True),
        sa.Column("domain_id", sa.String(length=36), nullable=True),
        sa.Column("sender", sa.String(length=254), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("error_stage", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["smtp_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_send_attempts_created_at"),
        "send_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_send_attempts_domain_id"),
        "send_attempts",
        ["domain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_send_attempts_user_id"),
        "send_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sender_addresses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("domain_id", sa.String(length=36), nullable=False),
        sa.Column(
            "address",
            sa.String(length=254, collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id", "address"),
    )
    op.create_table(
        "sender_grants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("domain_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "address",
            sa.String(length=254, collation="utf8mb4_bin"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain_id", "user_id", "address"),
    )
    op.create_table(
        "smtp_configs",
        sa.Column("domain_id", sa.String(length=36), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("security", sa.String(length=16), nullable=False),
        sa.Column("auth", sa.String(length=16), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password_encrypted", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "auth = 'none' OR (security IN ('starttls', 'tls') "
            "AND username IS NOT NULL AND password_encrypted IS NOT NULL)"
        ),
        sa.CheckConstraint("auth IN ('none', 'password')"),
        sa.CheckConstraint("security IN ('none', 'starttls', 'tls')"),
        sa.CheckConstraint("port BETWEEN 1 AND 65535"),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domains.id"],
        ),
        sa.PrimaryKeyConstraint("domain_id"),
    )
    op.create_table(
        "send_recipients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("address", sa.String(length=254), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["send_attempts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_send_recipients_attempt_id"),
        "send_recipients",
        ["attempt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this schema revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_send_recipients_attempt_id"), table_name="send_recipients"
    )
    op.drop_table("send_recipients")
    op.drop_table("smtp_configs")
    op.drop_table("sender_grants")
    op.drop_table("sender_addresses")
    op.drop_index(op.f("ix_send_attempts_user_id"), table_name="send_attempts")
    op.drop_index(
        op.f("ix_send_attempts_domain_id"), table_name="send_attempts"
    )
    op.drop_index(
        op.f("ix_send_attempts_created_at"), table_name="send_attempts"
    )
    op.drop_table("send_attempts")
    op.drop_table("domain_admins")
    op.drop_table("credential_scopes")
    op.drop_index(op.f("ix_web_sessions_user_id"), table_name="web_sessions")
    op.drop_index(
        op.f("ix_web_sessions_expires_at"), table_name="web_sessions"
    )
    op.drop_table("web_sessions")
    op.drop_index(
        op.f("ix_smtp_credentials_user_id"), table_name="smtp_credentials"
    )
    op.drop_table("smtp_credentials")
    op.drop_index(op.f("ix_invitations_user_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_domains_owner_user_id"), table_name="domains")
    op.drop_table("domains")
    op.drop_table("users")
    op.drop_index(op.f("ix_rate_limits_expires_at"), table_name="rate_limits")
    op.drop_table("rate_limits")
    # ### end Alembic commands ###
